variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_NAME: $POSTGRES_NAME
  POSTGRES_ROOT_PASSWORD: $POSTGRES_ROOT_PASSWORD
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD

stages:
  - build
  - test
  - push
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

after_script:
  - docker logout $CI_REGISTRY || true

build-image:
  stage: build
  tags: 
    - bare
  script:
    - env
    - docker build -t git.lnmo.ru/lcme/achievements:latest -t git.lnmo.ru/lcme/achievements:${VERSION_TAG}  .

test-image:
  stage: test
  tags:
    - bare
  script:
    - docker run git.lnmo.ru/lcme/achievements:latest python "cd achievements && python manage.py test && python manage.py check"

push-image:
  stage: push
  tags:
    - bare
  script:
    - docker push git.lnmo.ru/lcme/achievements:latest
    - docker push git.lnmo.ru/lcme/achievements:${VERSION_TAG}

deploy-2-production:
  stage: deploy
  tags:
    - bare
  script:
    - "echo TODO: Migrate, run"
  environment:
    name: production
    url: https://results.lnmo.ru
  when: manual