variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_NAME: $POSTGRES_DB
  POSTGRES_ROOT_PASSWORD: $POSTGRES_PASS
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASS

default:
  image: python:3
  tags:
    - docker
  services:
    - postgres
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - cd achievements
    - pwd
    - ls -la
    - python -m pip install --upgrade pip
    - pip3 install -r requirements.txt


migrations:
  tags:
    - docker
  stage: build
  script:
    - cd achievements
    - python3 manage.py makemigrations
    # - python3 manage.py makemigrations myapp
    - python3 manage.py migrate
    - python3 manage.py check


django-tests:
  tags:
    - docker
  stage: test
  script:
    - cd achievements
    - python3 manage.py test


deploy:
  tags:
    - docker
  stage: deploy
  script:
    - cd achievements
    - python3 manage.py runserver 0.0.0.0:8000
