# Re-define variables bacause we can :<
variables: 
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_NAME: $POSTGRES_NAME
  POSTGRES_ROOT_PASSWORD: $POSTGRES_ROOT_PASSWORD
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD

default:
  image: python:3
  tags:
    - docker
  services:
    - name: postgres
      alias: db
  cache:
    paths:
      - ~/.cache/pip/
  before_script:
    - env
    - cd achievements
    - python -m pip install --upgrade pip
    - pip3 install -r requirements.txt


migrations:
  tags:
    - docker
  stage: build
  script:
    - python3 manage.py makemigrations
    # - python3 manage.py makemigrations myapp
    - python3 manage.py migrate
    - python3 manage.py check


django-tests:
  tags:
    - docker
  stage: test
  script:
    - python3 manage.py test


deploy:
  tags:
    - docker
  stage: deploy
  script:
    - python3 manage.py runserver 0.0.0.0:8000
  environment:
    name: production
    url: https://results.lnmo.ru
