# Generated by Django 4.0.4 on 2022-06-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseparticipation',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='Оценка за экзамен?'),
        ),
    ]
