# Generated by Django 4.0.4 on 2022-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_courseparticipation_is_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='is_team_member',
            field=models.BooleanField(default=False, null=True, verbose_name='В составе команды'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='prize',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Награда'),
        ),
        migrations.AlterField(
            model_name='olympiadparticipation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Звание'),
        ),
    ]
